apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend # == pod template: labels
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: install
        image: rurumimic/wget
        command: 
        - wget
        - --no-check-certificate
        - -k # --convert-links
        - -O # --output-document=FILE
        - /init/bauhaus.html
        - https://en.wikipedia.org/wiki/Bauhaus
        volumeMounts:
        - name: init
          mountPath: /init
      containers:
        - name: app
          image: node-app
          imagePullPolicy: Never
          ports:
          - containerPort: 3000
          env:
            - name: MYSQL_HOST
              value: mariadb-service
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mariadb-conf
                  key: mysql_database
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mariadb-conf
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mariadb-conf
                  key: mysql_password
          volumeMounts:
            - name: mariadb-config
              mountPath: /config/mariadb
              readOnly: true
        - name: proxy
          image: nginx:alpine
          ports:
          - containerPort: 80
          volumeMounts:
            - name: init
              mountPath: /usr/share/nginx/html/init
              readOnly: true
            - name: nginx-conf-file
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: default-conf-file
              mountPath: /etc/nginx/templates/default.conf.template
              subPath: default.conf.template
              readOnly: true
      volumes:
        - name: init
          emptyDir: {}
        - name: nginx-conf-file
          configMap:
            name: nginx-conf
        - name: default-conf-file
          configMap:
            name: default-conf
        - name: mariadb-config
          configMap:
            name: mariadb-conf
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP # or NodePort
  selector:
    app: backend # == pod template: labels
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80 # == pod template: spec ports container port
