apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app # == pod template: labels
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend
        image: express-app
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  # type: LoadBalancer # localhost:3001
  selector:
    app: backend-app # == pod template: labels
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000 # == pod template: spec ports container port
