apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend # == pod template: labels
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: app
        image: node-app
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
      - name: proxy
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf-file
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: default-conf-file
          mountPath: /etc/nginx/templates/default.conf.template
          subPath: default.conf.template
          readOnly: true
      volumes:
      - name: nginx-conf-file
        configMap:
          name: nginx-conf
      - name: default-conf-file
        configMap:
          name: default-conf
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer # localhost expose
  selector:
    app: backend # == pod template: labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # == pod template: spec ports container port
