apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web # == pod template: labels
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf-file
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: default-conf-file
          mountPath: /etc/nginx/templates/default.conf.template
          subPath: default.conf.template
          readOnly: true
      volumes:
      - name: nginx-conf-file
        configMap:
          name: nginx-conf
      - name: default-conf-file
        configMap:
          name: default-conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer # localhost expose
  selector:
    app: nginx-web # == pod template: labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # == pod template: spec ports container port
